# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT covid_vaccine.wsgi

runtime_config:
  python_version: 3.7

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
# [END runtime]